"""
TriageAI Tools — Gemini API Utility
Uses Google Gemini (gemini-2.0-flash) for ultra-fast structured clinical JSON.
Each agent calls call_gemini() to get a JSON response.

Model used: gemini-2.0-flash (default) — configurable via GEMINI_MODEL env var.
"""

import json
import os
import re
import google.generativeai as genai

_client = None


def _get_client():
    global _client
    if _client is None:
        api_key = os.environ.get("GEMINI_API_KEY", "")
        if not api_key:
            raise RuntimeError("GEMINI_API_KEY environment variable is not set")
        genai.configure(api_key=api_key)
        model_name = os.environ.get("GEMINI_MODEL", "gemini-2.0-flash")
        _client = genai.GenerativeModel(
            model_name=model_name,
            generation_config=genai.GenerationConfig(
                temperature=0.2,
                max_output_tokens=800,
                response_mime_type="application/json",
            ),
        )
    return _client


def call_gemini(system: str, user: str, max_tokens: int = 800) -> str:
    """
    Call Gemini with a system + user prompt.
    Returns the raw text response string or a JSON error string.
    """
    try:
        client = _get_client()
        combined_prompt = f"{system}\n\n{user}"
        response = client.generate_content(combined_prompt)
        
        # Check if response has text (might be blocked or empty)
        if not response.candidates or not response.candidates[0].content.parts:
            return json.dumps({"error": "No response generated by Gemini", "details": str(response.prompt_feedback)})
            
        return response.text
    except Exception as e:
        error_msg = str(e)
        print(f"  [GEMINI ERROR] {error_msg}", flush=True)
        if "429" in error_msg or "ResourceExhausted" in error_msg:
            return json.dumps({
                "error": "Gemini API Quota Exhausted (429)",
                "details": "Your prepayment credits are depleted or rate limit hit. Please check AI Studio billing."
            })
        return json.dumps({"error": f"Gemini API Error: {error_msg}"})


def parse_llm_json(raw_text: str) -> dict:
    """
    Strip markdown code fences from a Gemini response and parse as JSON.
    Returns {'raw': ..., 'error': 'parse_failed'} on failure.
    """
    clean = raw_text.strip()

    if clean.startswith("```json"):
        clean = clean[len("```json"):]
    elif clean.startswith("```"):
        clean = clean[len("```"):]

    if clean.endswith("```"):
        clean = clean[:-len("```")]

    clean = clean.strip()

    try:
        return json.loads(clean)
    except json.JSONDecodeError:
        match = re.search(r"\{.*\}", clean, re.DOTALL)
        if match:
            try:
                return json.loads(match.group())
            except json.JSONDecodeError:
                pass
        return {"raw": raw_text, "error": "parse_failed"}
